### ISSUE TITLE
Preg_match error on PHP 7.3

### ISSUE THREAD

**Issue by hostep** [Paazl/magento2-checkout-widget#47]
Hi guys

We get an error with this module after we upgraded from PHP 7.2 to 7.3 on https://github.com/Paazl/magento2-checkout-widget/blob/d8e4d5729e5bb82a541654db672865a93260a292/Model/Api/Builder/Order.php#L188-L191

The error is:
```
PHP Warning:  preg_match(): Compilation failed: escape sequence is invalid in character class at offset 18 in
```

If I remove that `\R` from the regex, it works again. Can anybody elaborate what that `\R` escape sequence is, because I've never seen that one before in a regex?
Can we safely remove that `\R` escape sequence?

Can somebody confirm this problem?

More details about environment:
```
Fails on:
PHP 7.3.16
PCRE Library Version => 10.35 2020-05-09
PCRE Unicode Version => 13.0.0

Fails on:
PHP 7.3.18
PCRE Library Version => 10.34 2019-11-21
PCRE Unicode Version => 12.1.0

Works on:
7.2.29
PCRE Library Version => 8.44 2020-02-12
```

Thanks!

**Comment by hostep** [comment]
Also, what's up with that regex only allowing 2 characters in the house number extension? That is way too strict in my opinion.

We have addresses like these which fail against these regexes:
- Remi Vandervaerenlaan 7/0202
- Nijverheidstraat 22 bus1.1

@Marvin-Magmodules: can you have a look when you have a bit of time? Thanks!

**Comment by Marvin-Magmodules** [comment]
Hi @hostep, thanks for the issue report. We will add this to the schedule in the coming days and get back to you!

**Comment by Marvin-Magmodules** [comment]
@hostep, sorry for the long wait, we had some discussion about how to handle this case. First, 
about the PHP7.3, the construction `\R` is documented but seems to be incompatible with library pcre2-10.x so we've dropped this. 

Secondly we added an address parser as a fallback for regex. If this does not get the desired results, we pass the data to the Paazl API with house number 0 (as discusses with Paazl). 

Thanks for the examples, we've added these to our tests: [OrderTest.php](https://github.com/Paazl/magento2-checkout-widget/blob/1.2.4/Test/Unit/Model/Api/Builder/OrderTest.php#L97)

Code is not final yet (branche; [1.2.4](https://github.com/Paazl/magento2-checkout-widget/commits/1.2.4)), planned to review and finish this next week!

**Comment by hostep** [comment]
Thanks very much @Marvin-Magmodules!

We'll test this out (probably after 1.2.4 is finalised) and if we run into more addresses with problems, we'll let them know.

**Comment by Marvin-Magmodules** [comment]
Hi @hostep we have just released the [v1.3.0](https://github.com/Paazl/magento2-checkout-widget/releases/tag/1.3.0) version that has this implemented. Also added the Unit Test to Github Actions. Thank you again for the detailed reports and patience. We are closing this issue now but please feel free to reopen the issue if this still occurs.
